name: Upload to B2

on:
  push:
    branches:
      - main

jobs:
  upload-to-b2:
    runs-on: ubuntu-latest

    steps:
    # 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 全局安装 b2sdk
    - name: Install B2 CLI via pip
      run: pip install b2sdk

    # 使用 b2 工具进行授权
    - name: B2 CLI Authentication
      env:
        B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
        B2_ACCOUNT_KEY: ${{ secrets.B2_ACCOUNT_KEY }}
      run: b2 authorize-account $B2_ACCOUNT_ID $B2_ACCOUNT_KEY

    # 上传内容到 B2
    - name: Upload files to B2
      env:
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
      run: |
        mkdir upload_dir
        cp -r . upload_dir
        b2 sync --keepDays 0 --delete upload_dir b2://$B2_BUCKET_NAME

    # 清理临时文件
    - name: Clean up
      run: rm -rf upload_dir
